### PR TITLE
Adding Inauguration Day to MXMC

### PR DESCRIPTION
**Pull request by Andras1022**

### CODE REVIEW

**Review by jodastephen — CHANGES_REQUESTED** [review]
No. The original location (not module/basics) is the right location

**Comment by MichaelRol** [comment]
@jodastephen Are you referring to the .bin file itself or the `Path` in the script?

**Comment by jodastephen** [comment]
Both should be in the location they were before the recent change

**Comment by MichaelRol** [comment]
Yes, so this PR corrects the location of the update .bin file - the change of the Path is because the old path caused the issue where the binary was incorrectly generated outside of the /modules/basics package. Both @Andras1022 and myself have tested with the updated Path and it correctly updates the binary file inside /modules/basics

**Comment by jodastephen** [comment]
This appears to be an issue with IntelliJ, which uses a poor choice of Working Directory by default when running code. The tool is supposed to be run with a Working Directory of *strata-basics*, therefore there the extra `module/basics` is incorrect.

(Logically, once the source is compiled it has no knowledge of the original source code structure, so "module/basics" has no actual meaning at runtime. Eclipse's choice of working directory therefore makes much more sense here.)

**Comment by Andras1022** [comment]
@jodastephen I have removed the extra "module/basics" from the path, but in the original PR the binary file was an addition, now it's replacing the previous version.

**Review by jodastephen — APPROVED** [review]

**Pull request merged**
