### PR TITLE
Provide a factory method to configure decomposition function for CurveCalibrator

### PR DESCRIPTION
**Pull request by jurna**
Currently there is no possibility to provide a custom decomposition function to use in NewtonVectorRootFinder . Current SV decomposition implementation is based on apache commons math library, which is very inefficient. For bigger curve groups more efficient implementation is required. This pull request adds a new factory method (and new parameter in private constructor), which allows to configure a custom decomposition function.

### CODE REVIEW

**Comment by jodastephen** [comment]
Thanks for this PR. You are correct that there is no way to control the decomposition. However, your change uses an internal interface `Decomposition` on the public API, so another way will have to be found.

Looking at the change, we at OpenGamma are thinking that it may be better to allow the whole root finder to be passed into the calibrator, giving much more flexibility. We need to spend a little time evaluating the impact of that, so please bear with us.

**Comment by jurna** [comment]
Yes my initial idea was also to allow root finder to be passed into calibrator. But you are already passing parameters (toleranceAbs, toleranceRel, stepMaximum) into BroydenVectorRootFinder, so adding another parameter into factory method seemed like a better idea. But I've overlooked that Decomposition is a class in the internal the api.

**Comment by jodastephen** [comment]
Maybe something [like this](https://github.com/OpenGamma/Strata/commit/5b12f72819b4bfd20eec8e9938d8e13d826b8956). Not 100% sure yet.

**Comment by jurna** [comment]
The other solution would be to make Decomposition class a public interface. Because at the moment I would have to implement the whole new NewtonVectorRootFinder. It's not a big deal, just a thought.

**Comment by jodastephen** [comment]
Fixed by #1653, thanks

**Pull request closed without merging**
