### PR TITLE
Release/v1.5.x

### PR DESCRIPTION
**Pull request by imode69**
Support for FX Window Forwards  (FxFlexibleForward in FpML) - domain definitions and a simple "price to worst" model based on a strip of fx forwards over the exercise period. 

I have developed a product and model based on 1.5.1 and would like to submit for review

### CODE REVIEW

**Comment by jodastephen** [comment]
The description sound great, unfortunately, the PR doesn't contain your changes. Normally, you need to fork Strata first, then make your changes on a branch, and finally raise a PR. Please ask if unsure.

Note that we may also need you to sign a contributor agreement, please send an email to info@opengamma.com so we can contact you and discuss.

**Comment by jodastephen** [comment]
Is there anything we can do to help you get your code available for use to review?

**Comment by imode69** [comment]
My apologies, I'm completely new to Git so not quite familiar with the
workflow around a pull request. I assume I create a branch, push my changes
then make a pull request on that branch?

For now I'll do it "old school" and attach a zip of my source. As of now
I've implemented present value only. Also the model is very simplistic,
it's just a price to worse on a strip of forwards constructed during the
window period. I suppose a more sophisticated model would treat the window
as an american call structured with a down-and-out put but I guess that
might be overkill?

-regards
Richard


On Fri, Dec 1, 2017 at 3:51 AM, Stephen Colebourne <notifications@github.com

**Comment by jodastephen** [comment]
[This guide](https://gist.github.com/Chaser324/ce0505fbed06b947d962) is pretty good for the normal github workflow. However, I suspect you've already cloned Strata and done work on a branch. The trick here is to do the following:

* Fork Strata (button in top right)
* [Add a remote](https://help.github.com/articles/adding-a-remote/) to your fork. ie. Go to your local copy of Strata and do `git remote add myfork https://github.com/imode69/Strata.git`. This means that your code is now linked to the original Strata as "origin" and your fork as "myfork".
* Push your branch to your fork `git push -u myfork <branch>`
* Go to the website of your fork, and you should be able to raise a new Pull Request from there with all of your files in it

I think thats everything, but it might be worth taking a zipped copy of your local directory before starting.
thanks

**Comment by imode69** [comment]
Thanks for the info, very helpful. Been using Perforce and SVN most of my
career so git is still a bit "foreign" to me.

regards
Richard

On Sat, Dec 2, 2017 at 1:57 AM, Stephen Colebourne <notifications@github.com

**Pull request closed without merging**
