### PR TITLE
100th Polish independence anniversary - 2018.11.12

### PR DESCRIPTION
**Pull request by szlapinski**
The Polish government is about to decide that the 100th Polish independence anniversary will be celebrated on 2018.11.12
https://translate.google.com/translate?sl=pl&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fwww.money.pl%2Fgielda%2Fwiadomosci%2Fartykul%2Fjak-swieto-to-swieto-gielda-bez-sesji-12%2C171%2C0%2C2420139.html&edit-text=
The Parlament will vote for this on the 7th of November session.

### CODE REVIEW

**Comment by szlapinski** [comment]
By the way: I've noticed that Polish holidays are based on government law and stock exchange holidays. The latter are not official holidays in Poland. What is your policy for this Holiday Calendar Class? Is it for stock exchange purpose or just official holidays?

**Comment by jodastephen** [comment]
The holiday calendar here is intended to match the days used to fix the WIBOR interest rate index. Any links you can provide that detail the actual days of that calendar would be appreciated. I'll merge this once I hear back to confirm that the change is correct wrt to WIBOR. Thanks

**Comment by szlapinski** [comment]
> The holiday calendar here is intended to match the days used to fix the WIBOR interest rate index. Any links you can provide that detail the actual days of that calendar would be appreciated. I'll merge this once I hear back to confirm that the change is correct wrt to WIBOR. Thanks

Do you need a formal confirmation or is this Warsaw Stock Exchange Management Board Resolution enough:
https://www.gpw.pl/gpw-management-board-resolutions?cmn_id=107601&title=Resolution+No.+1104%2F2018&ph_main_01_start=show
?

**Comment by jodastephen** [comment]
Merged thanks

**Comment by szlapinski** [comment]
Thanks for merging. What is your release cycle? When it will be available in a new version?

**Comment by jodastephen** [comment]
v2.1.1 released

**Comment by jodastephen** [comment]
v2.1.2 released

**Pull request merged**
